const getImageUrl = (id) => `https://picsum.photos/200/300?random=${id}`;

let restaurantList = [
  {
    restaurantName: "Starbucks",
    restaurantCuisine: ["Cold coffee", "Hot coffee", "capaccino"], //subtitle
    avgRating: "4.1",
    restaurantId: "1",
    deliveryTime: "30 mins",
    imageUrl: getImageUrl(1),
  },
  {
    restaurantName: "KFC",
    restaurantCuisine: ["Burger", "Chicken tikka", "Leg piece"],
    avgRating: "2.4",
    restaurantId: "2",
    deliveryTime: "25 mins",
    imageUrl: getImageUrl(2),
  },
  {
    restaurantName: "Dominos",
    restaurantCuisine: ["pizza", "hot pizza", "chilli pizza"],
    avgRating: "4.3",
    restaurantId: "3",
    deliveryTime: "40 mins",
    imageUrl: getImageUrl(3),
  },
  {
    restaurantName: "McDonald's",
    restaurantCuisine: ["Burger", "Fries", "Nuggets"],
    avgRating: "4.0",
    restaurantId: "4",
    deliveryTime: "20 mins",
    imageUrl: getImageUrl(4),
  },
  {
    restaurantName: "Pizza Hut",
    restaurantCuisine: ["Pizza", "Pasta", "Garlic Bread"],
    avgRating: "3.8",
    restaurantId: "5",
    deliveryTime: "35 mins",
    imageUrl: getImageUrl(5),
  },
  {
    restaurantName: "Subway",
    restaurantCuisine: ["Sandwich", "Salad", "Wrap"],
    avgRating: "4.2",
    restaurantId: "6",
    deliveryTime: "15 mins",
    imageUrl: getImageUrl(6),
  },
  {
    restaurantName: "Burger King",
    restaurantCuisine: ["Burger", "Fries", "Shake"],
    avgRating: "3.9",
    restaurantId: "7",
    deliveryTime: "22 mins",
    imageUrl: getImageUrl(7),
  },
  {
    restaurantName: "Taco Bell",
    restaurantCuisine: ["Taco", "Burrito", "Nachos"],
    avgRating: "4.1",
    restaurantId: "8",
    deliveryTime: "28 mins",
    imageUrl: getImageUrl(8),
  },
  {
    restaurantName: "Chipotle",
    restaurantCuisine: ["Burrito", "Bowl", "Taco"],
    avgRating: "4.3",
    restaurantId: "9",
    deliveryTime: "18 mins",
    imageUrl: getImageUrl(9),
  },
  {
    restaurantName: "Panda Express",
    restaurantCuisine: ["Orange Chicken", "Fried Rice", "Noodles"],
    avgRating: "3.7",
    restaurantId: "10",
    deliveryTime: "30 mins",
    imageUrl: getImageUrl(10),
  },
  {
    restaurantName: "Chick-fil-A",
    restaurantCuisine: ["Chicken Sandwich", "Waffle Fries", "Salad"],
    avgRating: "4.5",
    restaurantId: "11",
    deliveryTime: "20 mins",
    imageUrl: getImageUrl(11),
  },
  {
    restaurantName: "Five Guys",
    restaurantCuisine: ["Burger", "Fries", "Shake"],
    avgRating: "4.0",
    restaurantId: "12",
    deliveryTime: "25 mins",
    imageUrl: getImageUrl(12),
  },
  {
    restaurantName: "Dunkin'",
    restaurantCuisine: ["Donuts", "Coffee", "Bagel"],
    avgRating: "3.9",
    restaurantId: "13",
    deliveryTime: "15 mins",
    imageUrl: getImageUrl(13),
  },
  {
    restaurantName: "Panera Bread",
    restaurantCuisine: ["Soup", "Salad", "Sandwich"],
    avgRating: "4.2",
    restaurantId: "14",
    deliveryTime: "20 mins",
    imageUrl: getImageUrl(14),
  },
  {
    restaurantName: "Wendy's",
    restaurantCuisine: ["Burger", "Fries", "Frosty"],
    avgRating: "3.8",
    restaurantId: "15",
    deliveryTime: "22 mins",
    imageUrl: getImageUrl(15),
  },
];

export default restaurantList;